import React, { useState } from 'react';
import { 
  FileText, 
  Calendar, 
  User, 
  DollarSign, 
  Edit, 
  Eye, 
  Printer,
  Plus,
  Search,
  Filter
} from 'lucide-react';
import { useInventory } from '../context/InventoryContext';
import { useAuth } from '../context/AuthContext';
import BillModal from '../components/BillModal';
import './Bills.css';

function Bills() {
  const { bills, products, addBill, updateBill } = useInventory();
  const { user } = useAuth();
  const [searchTerm, setSearchTerm] = useState('');
  const [dateFilter, setDateFilter] = useState('');
  const [selectedBill, setSelectedBill] = useState(null);
  const [showBillModal, setShowBillModal] = useState(false);
  const [isCreatingBill, setIsCreatingBill] = useState(false);

  // Filter bills
  const filteredBills = bills.filter(bill => {
    const matchesSearch = bill.customerName.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         bill.id.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesDate = !dateFilter || bill.date === dateFilter;
    return matchesSearch && matchesDate;
  });

  const handleViewBill = (bill) => {
    setSelectedBill(bill);
    setShowBillModal(true);
    setIsCreatingBill(false);
  };

  const handleEditBill = (bill) => {
    setSelectedBill(bill);
    setShowBillModal(true);
    setIsCreatingBill(false);
  };

  const handleCreateBill = () => {
    setSelectedBill(null);
    setShowBillModal(true);
    setIsCreatingBill(true);
  };

  const handleSaveBill = (billData) => {
    if (isCreatingBill) {
      addBill(billData);
    } else {
      updateBill(billData);
    }
    setShowBillModal(false);
    setSelectedBill(null);
  };

  const handlePrintBill = (bill) => {
    // Create a printable version
    const printWindow = window.open('', '_blank');
    const printContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Bill ${bill.id}</title>
          <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
            .store-info { margin-bottom: 10px; }
            .store-name { font-size: 24px; font-weight: bold; color: #333; margin-bottom: 5px; }
            .store-address { font-size: 14px; color: #666; line-height: 1.4; }
            .bill-title { font-size: 20px; font-weight: bold; margin-top: 15px; color: #0ea5e9; }
            .bill-info { margin-bottom: 20px; }
            .bill-info p { margin: 5px 0; }
            .items-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            .items-table th, .items-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            .items-table th { background-color: #f2f2f2; font-weight: bold; }
            .total { text-align: right; font-weight: bold; font-size: 18px; margin-top: 20px; }
            .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="store-info">
              <div class="store-name">${user?.storeName || 'SmartInventory Store'}</div>
              <div class="store-address">
                ${user?.address || ''}<br>
                ${user?.city || ''}, ${user?.state || ''} - ${user?.pincode || ''}
              </div>
            </div>
            <div class="bill-title">Sales Bill</div>
          </div>
          <div class="bill-info">
            <p><strong>Bill ID:</strong> ${bill.id}</p>
            <p><strong>Date:</strong> ${new Date(bill.date).toLocaleDateString()}</p>
            <p><strong>Customer:</strong> ${bill.customerName}</p>
          </div>
          <table class="items-table">
            <thead>
              <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              ${bill.items.map(item => `
                <tr>
                  <td>${item.productName}</td>
                  <td>${item.quantity}</td>
                  <td>₹${item.finalPrice.toFixed(2)}</td>
                  <td>₹${(item.quantity * item.finalPrice).toFixed(2)}</td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="total">
            <p>Total Amount: ₹${bill.totalAmount.toFixed(2)}</p>
          </div>
          <div class="footer">
            <p>Thank you for your business!</p>
            <p>Generated by SmartInventory Management System</p>
          </div>
        </body>
      </html>
    `;
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.print();
  };

  const getTotalRevenue = () => {
    return filteredBills.reduce((sum, bill) => sum + bill.totalAmount, 0);
  };

  const getTotalBills = () => {
    return filteredBills.length;
  };

  const getAverageOrderValue = () => {
    const total = getTotalRevenue();
    const count = getTotalBills();
    return count > 0 ? total / count : 0;
  };

  return (
    <div className="bills">
      <div className="bills-header">
        <div className="header-content">
          <h1>Bills & Sales History</h1>
          <p>Track all sales with flexible pricing options</p>
        </div>
        <button onClick={handleCreateBill} className="btn btn-primary create-bill-btn">
          <Plus size={16} />
          Create New Bill
        </button>
      </div>

      {/* Stats Cards */}
      <div className="bills-stats">
        <div className="stat-card">
          <div className="stat-icon">
            <FileText />
          </div>
          <div className="stat-content">
            <span className="stat-value">{getTotalBills()}</span>
            <span className="stat-label">Total Bills</span>
          </div>
        </div>
        
        <div className="stat-card">
          <div className="stat-icon">
            <DollarSign />
          </div>
          <div className="stat-content">
            <span className="stat-value">₹{getTotalRevenue().toFixed(2)}</span>
            <span className="stat-label">Total Revenue</span>
          </div>
        </div>
        
        <div className="stat-card">
          <div className="stat-icon">
            <Calendar />
          </div>
          <div className="stat-content">
            <span className="stat-value">₹{getAverageOrderValue().toFixed(2)}</span>
            <span className="stat-label">Avg Order Value</span>
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="bills-filters">
        <div className="search-box">
          <Search className="search-icon" />
          <input
            type="text"
            placeholder="Search by customer name or bill ID..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
        </div>
        
        <div className="filter-group">
          <Filter className="filter-icon" />
          <input
            type="date"
            value={dateFilter}
            onChange={(e) => setDateFilter(e.target.value)}
            className="date-filter"
          />
        </div>
      </div>

      {/* Bills Table */}
      <div className="table-container">
        <table className="table">
          <thead>
            <tr>
              <th>Bill ID</th>
              <th>Date</th>
              <th>Customer Name</th>
              <th>Total Items</th>
              <th>Total Amount</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredBills.length === 0 ? (
              <tr>
                <td colSpan="6" className="no-data">
                  <FileText className="no-data-icon" />
                  <span>No bills found</span>
                </td>
              </tr>
            ) : (
              filteredBills.map(bill => (
                <tr key={bill.id}>
                  <td className="bill-id">{bill.id}</td>
                  <td>{new Date(bill.date).toLocaleDateString()}</td>
                  <td>
                    <div className="customer-info">
                      <User className="customer-icon" />
                      <span>{bill.customerName}</span>
                    </div>
                  </td>
                  <td>{bill.items.reduce((sum, item) => sum + item.quantity, 0)}</td>
                  <td className="amount">₹{bill.totalAmount.toFixed(2)}</td>
                  <td>
                    <div className="actions">
                      <button
                        onClick={() => handleViewBill(bill)}
                        className="btn-icon btn-view"
                        title="View Bill"
                      >
                        <Eye size={16} />
                      </button>
                      <button
                        onClick={() => handleEditBill(bill)}
                        className="btn-icon btn-edit"
                        title="Edit Bill"
                      >
                        <Edit size={16} />
                      </button>
                      <button
                        onClick={() => handlePrintBill(bill)}
                        className="btn-icon btn-print"
                        title="Print Bill"
                      >
                        <Printer size={16} />
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Bill Modal */}
      {showBillModal && (
        <BillModal
          bill={selectedBill}
          products={products}
          isCreating={isCreatingBill}
          onSave={handleSaveBill}
          onClose={() => {
            setShowBillModal(false);
            setSelectedBill(null);
          }}
        />
      )}
    </div>
  );
}

export default Bills;